# datahub-gms-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: datahub-gms
  namespace: datahub
  labels:
    app: datahub-gms
spec:
  selector:
    app: datahub-gms
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
