apiVersion: v1
kind: Secret
metadata:
  name: datahub-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  mysql-username: {{ .Values.secrets.mysql.username | b64enc | quote }}
  mysql-password: {{ .Values.secrets.mysql.password | b64enc | quote }}
  mysql-database: {{ .Values.secrets.mysql.database | b64enc | quote }}
  mysql-root-password: {{ .Values.secrets.mysql.rootPassword | b64enc | quote }}
